### ISSUE TITLE
ya bot borked

### ISSUE THREAD

**Issue by dooly123** [codedcosmos/CometBot#2]

**Comment by codedcosmos** [comment]
What appears to be the issue?

**Comment by dooly123** [comment]
there are many issues

**Comment by dooly123** [comment]
jeez, when are you going to get back to me.

**Comment by codedcosmos** [comment]
what are the issues?

**Comment by dooly123** [comment]
I am having problems with my diet, can you assist in a well-balanced diet?

**Comment by codedcosmos** [comment]
Personally I recommend the Mediterranean diet.

It mainly consists of Vegetables, fruits whole grain, and healthy fats. You should be eating fish instead of beef and some dairy.

This is what I recommend to all my clients.

**Comment by dooly123** [comment]
thata nice but does it come in mens?

**Comment by codedcosmos** [comment]
It's a diet not a clothing size

**Comment by dooly123** [comment]
there is more to your gender then your clothing size
