### ISSUE TITLE
Error: A JNI error has occurred

### ISSUE THREAD

**Issue by SploeCyber** [codedcosmos/CometBot#3]
![Screenshot_2563_0504_185036](https://user-images.githubusercontent.com/37950018/80962935-319e6b80-8e38-11ea-8f3e-2f5da07698b7.png)
How can I fix it?

**Comment by SploeCyber** [comment]
![Screenshot_2563_0504_185301](https://user-images.githubusercontent.com/37950018/80963108-84782300-8e38-11ea-8dfd-f1d96ba5e8c4.png)

**Comment by codedcosmos** [comment]
If you download the new 1.8 release that should fix your issue. 
https://github.com/codedcosmos/CometBot/releases/tag/1.8

The original issue was caused by the bot being built in java 11 and you trying to run it with java 8. Comebot is now being built with java 8 instead.
